from . import category
from . import crm
from . import email
from . import pacchi
from . import product
from . import purchase
from . import res_partner
from . import sale
from . import stock
from . import tendina
from . import value_temp
